spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: slq3584167
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    naming:
      physical-strategy: org.hibernate:boot.model.naming.PhysicalNamingStrategyStandardImpl

flyway:
  enabled: true
  out-of-order: true
  encoding: UTF-8
  url: jdbc:mysql://localhost:3306
  schemas: testdb
  user: root
  password: slq3584167
